build:
  image: golang:latest
  environment:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
  commands:
    - cd cmd/cfssl
    - go get -v
    - go build -a -v

publish:
  docker:
    storage_driver: overlay
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: drone@profects.com
    repo: profects/cfssl
    file: .drone/cfssl/Dockerfile
    tag:
        - "latest"
        - "$$COMMIT"

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: drone
    channel: microservices